[server]
headless = true
address = "0.0.0.0"
port = 8501

[theme]
primaryColor = "#29B5E8"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false
